# Do this first 

BUILD_ROOT:=$(dir $(CURDIR)/$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))..
OUTPUT_DIR:=$(BUILD_ROOT)/output
MAKE:=make
DEPLOY_DIR:=/var/www/html/learnbashthehardway
BOOK_NAME:=learnbashthehardway
