=== Variables in Bash

As in any programming environment, variables are critical to an understanding
of bash. In this section you'll learn about variables in bash and some of their
subtleties.

==== Basic Variables

Start by creating a variable and echoing it.

----
1$ MYSTRING=astring
2$ echo $MYSTRING
----

Simple enough: you create a variable by stating its name, immediately adding an
equals sign, and then immediately stating the value.

Variables don't need to be capitalised, but they generally are by convention.

To get the value out of the variable, you have to use the dollar sign to tell
bash that you want the variable dereferenced.

==== Variables and Quoting

Things get more interesting when you start quoting.

Quoting used to group different 'words' into a variable value:

----
3$ MYSENTENCE=A sentence
4$ MYSENTENCE="A sentence"
5$ echo $MYSENTENCE
----

Since (by default) the shell reads each word in separated by a space, it thinks
the word 'sentence' is not related to the variable assigment, and treats it as a 
program. To get the sentence into the variable with the space is in it, you can
enclose it in the double quotes, as above.

Things get more interesting when we embed other variables in the quoted string:

----
6$ MYSENTENCE="A sentence with $MYSTRING in it"
7$ MYSENTENCE='A sentence with $MYSTRING in it'
----

If you were expecting similar behaviour to the previous section you may have got
a surprise!

This illustrated an important point if you're reading shell scripts: the bash
shell translates the variable into its value if it's in double quotes, but
does not if it's in single quotes.

Remember from the previous section that this is not true when globbing! Globs
are not expanded when in either single or double quotes. Confusing isn't it?

==== Shell Variables

Some variables are special, and set up when bash starts:

----
8$ echo $PPID          # Line 1
9$ PPID=nonsense       # Line 2
10$ echo $PPID          # Line 3
----

- Line 1 - PPID is a special variable set by the bash shell. It contains the bash's parent process id.
- Line 2 - Try and set the PPID variable to something else.
- Line 3 - Output PPID again.

What happened there?

If you want to make a readonly variable, put 'readonly' in front of it, like
this:

---- 
11$ readonly MYVAR=astring
12$ MYVAR=anotherstring
----

==== env

Wherever you are, you can see the variables that are set by running this:

----
13$ env
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
HISTSIZE=1000000
TMPDIR=/var/folders/mt/mrfvc55j5mg73dxm9jd3n4680000gn/T/
PERL5LIB=/home/imiell/perl5/lib/perl5
GOBIN=/space/go/bin
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.2BE31oXVrF/Render
TERM_PROGRAM_VERSION=361.1
PERL_MB_OPT=--install_base "/home/imiell/perl5"
TERM_SESSION_ID=07101F8B-1F4C-42F4-8EFF-1E8003E8A024
HISTFILESIZE=1000000
USER=imiell
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.uNwbe2XukJ/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/home/imiell/perl5/bin:/opt/local/bin:/opt/local/sbin:/Users/imiell/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/space/git/shutit:/space/git/work/bin:/space/git/home/bin:~/.dotfiles/bin:/space/go/bin
PWD=/space/git/work
LANG=en_GB.UTF-8
XPC_FLAGS=0x0
HISTCONTROL=ignoredups:ignorespace
XPC_SERVICE_NAME=0
HOME=/Users/imiell
SHLVL=2
PERL_LOCAL_LIB_ROOT=/home/imiell/perl5
LOGNAME=imiell
GOPATH=/space/go
DISPLAY=/private/tmp/com.apple.launchd.lwUJWwBy9y/org.macosforge.xquartz:0
SECURITYSESSIONID=186a7
PERL_MM_OPT=INSTALL_BASE=/home/imiell/perl5
HISTTIMEFORMAT=%d/%m/%y %T 
HISTFILE=/home/imiell/.bash_history
_=/usr/bin/env
OLDPWD=/Users/imiell/Downloads
----

The output will be different wherever you run it.


==== export

Type in these commands, and try to predict what will happen:

----
14$ MYSTRING=astring
15$ bash
16$ echo $MYSTRING
17$ exit
18$ echo $MYSTRING
19$ unset MYSTRING
20$ echo $MYSTRING
21$ export MYSTRING=anotherstring
22$ bash
23$ echo $MYSTRING
24$ exit
----

Based on this, what do you think export does?

You've already seen that a variable set in a bash terminal can be referenced
later by using the dollar sign.

But what happens when you set a variable, and then start up another process?

In this case, you set a variable (MYSTRING) to the value "astring", and then
start up a new bash shell process. Within that bash shell process, MYSTRING
does not exist, so an error is thrown. In other words, the variable was not
inherited by the bash process you just started.

After exiting that bash session, and unsetting the MYSTRING variable to ensure
it's gone, you set it again, but this time 'export' the variable, so that any
processes started by the running shell will have it in their environment. You
show this by starting up another bash shell, and it 'echo's the new value
"anotherstring" to the terminal.

It's not just shells that have environment variables! All processes have
environment variables.


==== Arrays

Worth mentioning here also are arrays. One such built-in, read only array is
BASH_VERSINFO. As in other languages, arrays in bash are zero-indexed.

Type out the following commands, which illustrate how to reference the version
information's major number: 

----
25$ bash --version
26$ echo $BASH_VERSINFO
27$ echo $BASH_VERSINFO[0]
28$ echo ${BASH_VERSINFO[0]}
29$ echo ${BASH_VERSINFO}
----

Arrays can be tricky to deal with, and bash doesn't give you much help!

The first thing to notice is that if the array will output the item at the first
element (0) if no index is given.

The second thing to notice is that simply adding [0] to a normal array reference
does not work. Bash treats the square bracket as a character not associated with
the variable and appends it to the end of the array.

You have to tell bash to treat the whole string "BASH_VERSION[0]" as the variable
to be dereferenced. You do this by using the curly braces.

These curly braces can be used on simple variables too:

----
30$ echo $BASH_VERSION_and_some_string
31$ echo ${BASH_VERSION}_and_some_string
----

In fact, 'simple variables' can be treated as arrays with one element!

----
32$ echo ${BASH_VERSION[0]}
----

So all bash variables are 'really' arrays!

Bash has 6 items (0-5) in its BASH_VERSINFO array:

----
33$ echo ${BASH_VERSINFO[1]}
34$ echo ${BASH_VERSINFO[2]}
35$ echo ${BASH_VERSINFO[3]}
36$ echo ${BASH_VERSINFO[4]}
37$ echo ${BASH_VERSINFO[5]}
38$ echo ${BASH_VERSINFO[6]}
----

As ever with variables, if the item does not exist then the output will be an
empty line.

==== Associative Arrays

TODO: http://www.artificialworlds.net/blog/2012/10/17/bash-associative-array-examples/

==== What you learned

- TODO

==== Exercises

1) Take the output of 'env' in your shell and work out why each item is there
and what it might be used by. You may want to use 'man bash', or use google to
figure it out. Or you could try re-setting it and see what happens.

2) Find out what the items in BASH_VERSINFO mean.
