This bash course has been written to help bash users to get to a deeper
understanding and proficiency in bash. It doesn't aim to make you an expert
immediately, but you will be more confident about using bash for more tasks than
just one-off commands.

==== Assumptions

It assumes some familiarity with very basic shell usage and commands. For those
looking to get to that point, I recommend following this set of mini-tutorials:

https://learnpythonthehardway.org/book/appendixa.html

It also assumes you are equipped with a bash shell and a terminal. If you're
unsure whether  you're in bash, type:

----
echo $BASH_VERSION
----

into your terminal. If you get a bash version string output then you in bash.

In this book, listings have a '$' sign 

==== How The Course Works

The course _demands_ that you type out all the exercises to follow it.

Frequently, the output will not be shown in the text, or even described.

Explanatory text will assume you typed it out. 

This is really important: you must get used to working in bash, and figuring out
what's going on by scratching your head and trying to work it out before I explain
it to you.

Each section is self-contained, and must be followed in full. To help show you
where you are, the shell commands are numbered 1-n, eg:

----
1$ #first command
2$ #second command
----

At the end of each section is a set of 'cleanup' commands (where needed) if you
want to use them.


==== What You Will Get

This course aims to give students:

- A hands-on, practical understanding of bash
- Enough information to understand what is going on as they go deeper into bash
- A familiarity with advanced bash usage


==== Structure

This book is structured into four parts:

===== Core Bash

Core foundational concepts essential for understanding bash. 

===== 'Level Two' Bash

Some more advanced concepts that are commonly-used in bash.

===== Tips

A primer on commonly-used techniques and features that are useful to know about.

===== Advanced Bash

Building on the first three chapters, and introducing some more advanced features, this chapters takes your bash skills beyond the norm.